# PWRP configuration file

storage_path = "/data"

# Recording-related configs
[recording]
repositories = [
    "github.com/cezarmathe/test.git"
]
protocol = "git"

    [recording.skips]
    missing_branch = false
    bad_url = false
    bad_protocol = false
    all = false

    [recording.generators]
        [[recording.generators.spec]]
            report_key = "last_update"
            task = "last-update"
            path = "~/.local/share/pwrp/cezarmathe/test"
                [[generators.spec.args]]
                usage = "command_arg"
                key = "last_update"
                value = ""